-- Database Schema Dump
-- Generated by Antigravity on 2025-12-27 (v1.2.0)
-- This reflects the current state of all migrations (3NF normalized)

-- ============================================
-- PREREQUISITE TABLES (No foreign key dependencies)
-- ============================================

CREATE TABLE "member_levels" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "slug" VARCHAR(50) NOT NULL UNIQUE,
    "name" VARCHAR(100) NOT NULL,
    "threshold" INTEGER NOT NULL DEFAULT 0,
    "discount" DECIMAL(5, 4) NOT NULL DEFAULT 0.0000,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE TABLE "stores" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL,
    "slug" VARCHAR UNIQUE,
    "email" VARCHAR NOT NULL UNIQUE,
    "address" TEXT NOT NULL,
    "phone" VARCHAR NOT NULL,
    "settings" TEXT,  -- JSON field for store-specific settings
    "status" VARCHAR NOT NULL DEFAULT 'active',
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE TABLE "categories" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL UNIQUE,
    "slug" VARCHAR NOT NULL UNIQUE,
    "description" TEXT,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE TABLE "coupons" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "code" VARCHAR NOT NULL UNIQUE,
    "discount_amount" INTEGER NOT NULL,
    "limit_price" INTEGER,
    "type" VARCHAR NOT NULL DEFAULT 'fixed',
    "starts_at" DATETIME,
    "ends_at" DATETIME,
    "usage_limit" INTEGER,
    "usage_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE INDEX "coupons_code_index" ON "coupons" ("code");
CREATE INDEX "coupons_starts_at_ends_at_index" ON "coupons" ("starts_at", "ends_at");

CREATE TABLE "special_events" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL,
    "discount_rate" DECIMAL(5, 4) NOT NULL,
    "starts_at" DATETIME,
    "ends_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE INDEX "special_events_starts_at_ends_at_index" ON "special_events" ("starts_at", "ends_at");

-- ============================================
-- CORE USER AND AUTHENTICATION TABLES
-- ============================================

CREATE TABLE "users" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL,
    "email" VARCHAR NOT NULL UNIQUE,
    "email_verified_at" DATETIME,
    "password" VARCHAR NOT NULL,
    "remember_token" VARCHAR,
    "role" VARCHAR NOT NULL DEFAULT 'customer',
    "phone" VARCHAR,
    "birthday" DATE,
    "store_id" INTEGER,
    "status" VARCHAR NOT NULL DEFAULT 'active',
    "balance" INTEGER NOT NULL DEFAULT 0,
    "member_level_id" INTEGER,
    "is_level_locked" TINYINT(1) NOT NULL DEFAULT 0,
    "last_login_at" DATETIME,
    "verification_code" VARCHAR,
    "verification_code_expires_at" DATETIME,
    "deleted_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE SET NULL,
    FOREIGN KEY ("member_level_id") REFERENCES "member_levels"("id") ON DELETE SET NULL
);

CREATE INDEX "users_email_index" ON "users" ("email");
CREATE INDEX "users_store_id_index" ON "users" ("store_id");
CREATE INDEX "users_member_level_id_index" ON "users" ("member_level_id");
CREATE INDEX "users_status_index" ON "users" ("status");
CREATE INDEX "users_deleted_at_email_index" ON "users" ("deleted_at", "email");

CREATE TABLE "personal_access_tokens" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "tokenable_type" VARCHAR NOT NULL,
    "tokenable_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "token" VARCHAR NOT NULL UNIQUE,
    "abilities" TEXT,
    "last_used_at" DATETIME,
    "expires_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" ON "personal_access_tokens" ("tokenable_type", "tokenable_id");

CREATE TABLE "password_reset_tokens" (
    "email" VARCHAR NOT NULL PRIMARY KEY,
    "token" VARCHAR NOT NULL,
    "created_at" DATETIME
);

CREATE TABLE "sessions" (
    "id" VARCHAR NOT NULL PRIMARY KEY,
    "user_id" INTEGER,
    "ip_address" VARCHAR(45),
    "user_agent" TEXT,
    "payload" TEXT NOT NULL,
    "last_activity" INTEGER NOT NULL
);

CREATE INDEX "sessions_user_id_index" ON "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" ON "sessions" ("last_activity");

-- ============================================
-- STORE AND PRODUCT TABLES
-- ============================================

CREATE TABLE "products" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL,
    "price" INTEGER NOT NULL,
    "original_price" INTEGER,
    "information" TEXT,
    "image" VARCHAR,
    "category_id" INTEGER,
    "status" VARCHAR NOT NULL DEFAULT 'active',
    "stock" INTEGER NOT NULL DEFAULT 0,
    "store_id" INTEGER NOT NULL,
    "deleted_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE,
    FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL
);

CREATE INDEX "products_store_id_index" ON "products" ("store_id");
CREATE INDEX "products_category_id_index" ON "products" ("category_id");
CREATE INDEX "products_status_index" ON "products" ("status");
CREATE INDEX "products_stock_index" ON "products" ("stock");
CREATE INDEX "products_deleted_at_status_index" ON "products" ("deleted_at", "status");

-- ============================================
-- CART TABLES
-- ============================================

CREATE TABLE "carts" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE INDEX "carts_user_id_index" ON "carts" ("user_id");

CREATE TABLE "cart_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "cart_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE CASCADE,
    FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE,
    UNIQUE ("cart_id", "product_id")
);

CREATE INDEX "cart_items_cart_id_index" ON "cart_items" ("cart_id");
CREATE INDEX "cart_items_product_id_index" ON "cart_items" ("product_id");

-- ============================================
-- ORDER TABLES (NORMALIZED)
-- ============================================

CREATE TABLE "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "status" VARCHAR NOT NULL DEFAULT 'pending_payment',
    "total_amount" INTEGER NOT NULL,
    "discount_amount" INTEGER NOT NULL DEFAULT 0,
    "shipping_fee" INTEGER NOT NULL DEFAULT 0,
    "payment_method" VARCHAR NOT NULL DEFAULT 'wallet',
    "logistics_number" VARCHAR,
    "coupon_id" INTEGER,
    "deleted_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE SET NULL
);

CREATE INDEX "orders_user_id_index" ON "orders" ("user_id");
CREATE INDEX "orders_status_index" ON "orders" ("status");
CREATE INDEX "orders_created_at_index" ON "orders" ("created_at");
CREATE INDEX "orders_coupon_id_index" ON "orders" ("coupon_id");
CREATE INDEX "orders_user_id_status_index" ON "orders" ("user_id", "status");
CREATE INDEX "orders_user_id_created_at_index" ON "orders" ("user_id", "created_at");
CREATE INDEX "orders_deleted_at_user_id_index" ON "orders" ("deleted_at", "user_id");

CREATE TABLE "order_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "price" INTEGER NOT NULL,
    "product_name" VARCHAR,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE,
    FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE
);

CREATE INDEX "order_items_order_id_index" ON "order_items" ("order_id");
CREATE INDEX "order_items_product_id_index" ON "order_items" ("product_id");

CREATE TABLE "order_item_options" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "order_item_id" INTEGER NOT NULL,
    "option_name" VARCHAR NOT NULL,
    "option_value" VARCHAR NOT NULL,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE CASCADE
);

CREATE INDEX "order_item_options_order_item_id_option_name_index" ON "order_item_options" ("order_item_id", "option_name");

CREATE TABLE "order_addresses" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "order_id" INTEGER NOT NULL,
    "name" VARCHAR,
    "phone" VARCHAR,
    "address" VARCHAR,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
);

CREATE INDEX "order_addresses_order_id_index" ON "order_addresses" ("order_id");
CREATE UNIQUE INDEX "order_addresses_order_id_unique" ON "order_addresses" ("order_id");

CREATE TABLE "order_snapshots" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "order_id" INTEGER NOT NULL UNIQUE,
    "buyer_email" VARCHAR(255),
    "member_level_name" VARCHAR(50),
    "user_name" VARCHAR(255),
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE
);

CREATE INDEX "order_snapshots_order_id_index" ON "order_snapshots" ("order_id");

-- ============================================
-- WALLET AND FINANCIAL TABLES
-- ============================================

CREATE TABLE "wallet_transactions" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "order_id" INTEGER,
    "type" VARCHAR NOT NULL,
    "amount" INTEGER NOT NULL,
    "description" VARCHAR,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL
);

CREATE INDEX "wallet_transactions_user_id_index" ON "wallet_transactions" ("user_id");
CREATE INDEX "wallet_transactions_type_index" ON "wallet_transactions" ("type");
CREATE INDEX "wallet_transactions_order_id_index" ON "wallet_transactions" ("order_id");
CREATE INDEX "wallet_transactions_user_id_type_index" ON "wallet_transactions" ("user_id", "type");

CREATE TABLE "wallet_logs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "wallet_transaction_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "operator_id" INTEGER,
    "operator_type" VARCHAR NOT NULL DEFAULT 'user',  -- enum: user, admin, system
    "action" VARCHAR(50) NOT NULL,
    "amount" INTEGER NOT NULL,
    "balance_before" INTEGER NOT NULL,
    "balance_after" INTEGER NOT NULL,
    "ip_address" VARCHAR(45),
    "user_agent" TEXT,
    "reason" TEXT,
    "checksum" VARCHAR(64),
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("wallet_transaction_id") REFERENCES "wallet_transactions"("id") ON DELETE CASCADE,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE SET NULL
);

CREATE INDEX "wallet_logs_user_id_created_at_index" ON "wallet_logs" ("user_id", "created_at");
CREATE INDEX "wallet_logs_operator_id_index" ON "wallet_logs" ("operator_id");
CREATE INDEX "wallet_logs_action_index" ON "wallet_logs" ("action");

-- ============================================
-- USER DATA TABLES
-- ============================================

CREATE TABLE "addresses" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "recipient_name" VARCHAR NOT NULL,
    "phone" VARCHAR NOT NULL,
    "city" VARCHAR NOT NULL,
    "district" VARCHAR NOT NULL,
    "zip_code" VARCHAR NOT NULL,
    "detail_address" VARCHAR NOT NULL,
    "is_default" TINYINT(1) NOT NULL DEFAULT 0,
    "deleted_at" DATETIME,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE INDEX "addresses_user_id_index" ON "addresses" ("user_id");

CREATE TABLE "favorites" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "notify_on_restock" TINYINT(1) NOT NULL DEFAULT 0,
    "notify_on_price_drop" TINYINT(1) NOT NULL DEFAULT 0,
    "created_at" DATETIME,
    "updated_at" DATETIME,
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE,
    UNIQUE ("user_id", "product_id")
);

CREATE INDEX "favorites_user_id_index" ON "favorites" ("user_id");
CREATE INDEX "favorites_product_id_index" ON "favorites" ("product_id");

-- ============================================
-- SYSTEM TABLES
-- ============================================

CREATE TABLE "settings" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "key" VARCHAR NOT NULL UNIQUE,
    "value" TEXT,
    "description" VARCHAR,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

CREATE TABLE "sequences" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR NOT NULL UNIQUE,
    "current_value" INTEGER NOT NULL DEFAULT 0,
    "created_at" DATETIME,
    "updated_at" DATETIME
);

-- ============================================
-- LARAVEL QUEUE AND JOB TABLES
-- ============================================

CREATE TABLE "cache" (
    "key" VARCHAR NOT NULL PRIMARY KEY,
    "value" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL
);

CREATE TABLE "cache_locks" (
    "key" VARCHAR NOT NULL PRIMARY KEY,
    "owner" VARCHAR NOT NULL,
    "expiration" INTEGER NOT NULL
);

CREATE TABLE "jobs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "queue" VARCHAR NOT NULL,
    "payload" TEXT NOT NULL,
    "attempts" INTEGER NOT NULL,
    "reserved_at" INTEGER,
    "available_at" INTEGER NOT NULL,
    "created_at" INTEGER NOT NULL
);

CREATE INDEX "jobs_queue_index" ON "jobs" ("queue");

CREATE TABLE "job_batches" (
    "id" VARCHAR NOT NULL PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "total_jobs" INTEGER NOT NULL,
    "pending_jobs" INTEGER NOT NULL,
    "failed_jobs" INTEGER NOT NULL,
    "failed_job_ids" TEXT NOT NULL,
    "options" TEXT,
    "cancelled_at" INTEGER,
    "created_at" INTEGER NOT NULL,
    "finished_at" INTEGER
);

CREATE TABLE "failed_jobs" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "uuid" VARCHAR NOT NULL UNIQUE,
    "connection" TEXT NOT NULL,
    "queue" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "exception" TEXT NOT NULL,
    "failed_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- MIGRATION TRACKING
-- ============================================

CREATE TABLE "migrations" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "migration" VARCHAR NOT NULL,
    "batch" INTEGER NOT NULL
);
